
---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  remote.services:
    Bookshop1:
      type: "odata-v4"
      destination:
        name: "bookshop1"
  data-source.auto-config.enabled: false
  odata-v4:
    endpoint.path: "/api"
  security:
    authentication.normalize-provider-tenant: true
    mock.users:
      admin:
        password: admin
        roles:
        - admin
        attributes:
          businessPartner:
          - "10401010"
      user:
        password: user  

      privi:
        password: privi
        privileged: true
---
spring:
  config.activate.on-profile: cloud
cds:
  remote.services:
    # Bookshop1:
    #   type: "odata-v4"
    #   destination:
    #     name: "bookshop1"
    #     tokenExchangeStrategy: "ForwardUserToken"
    Bookshop1:
      binding:
        name: bookshop-auth
        options:
          url: https://rmtest-rmcfkvpr-myspace-bookshop1-srv.cfapps.sap.hana.ondemand.com/odata/v4